### ISSUE TITLE
Performance and virtual dom Questions

### ISSUE THREAD

**Issue by Autumnlight02** [fb55/css-select#1007]
Is this css select library faster than the element.match api? And is there a html parser which allows me to match any valid css selector virtually?

**Comment by fb55** [comment]
What environment are you using?

**Comment by Autumnlight02** [comment]
Chrome, wanna use it in a webworker

**Comment by fb55** [comment]
You probably want to use Cheerio inside your web worker (using the slim export if you want to save some bytes). Besides that, is there a `element.match` API you can use in a web worker?
