### ISSUE TITLE
unmatched pseudo-class :active

### ISSUE THREAD

**Issue by astoilkov** [fb55/css-select#106]
`a:active` throws an error when provided as the selector parameter

**Comment by fb55** [comment]
How would you expect this to work?

**Comment by astoilkov** [comment]
I would expect to return false (not match) not throw an error. Catching error is slow and creates an ugly code when not needed.

```
try {
  do()
} catch (err) { }
```

**Comment by fb55** [comment]
A bit late, but pseudo-classes can be added to css-select. As there is no correct behavior here, I would ask users to add these classes themselves if they need them.
