### ISSUE TITLE
Describe how to use css-select with Cheerio?

### ISSUE THREAD

**Issue by gajus** [fb55/css-select#110]
I _grepped_ the documentation for [Cheerio](https://github.com/cheeriojs/cheerio) and didn't find anything. In Node.js environment, `css-select` would be predominantly useful in combination with Cheerio. As such, it would be useful to have general guidance about how the two projects interoperate.

**Comment by strarsis** [comment]
@gajus: I implented css selector support using this css-select library in svgo, 
this code may be helpful: https://github.com/svg/svgo/blob/2523799a12545a4035557043ee343945a7b7830f/lib/svgo/css-select-adapter.js
It is an adapter which itself uses a base adapter to further reduce the required code.

**Comment by fb55** [comment]
> Edit: cheerio internally uses jsdom.

cheerio uses parse5 to parse HTML and css-select to query the resulting document. 

css-select is already the query engine for cheerio, so nothing needs to be done to make this happen.
