### ISSUE TITLE
Can't use css-select from CDN

### ISSUE THREAD

**Issue by aurium** [fb55/css-select#1131]
If you try something like:
```js
import { selectOne, selectAll } from 'https://cdn.jsdelivr.net/npm/css-select@5.1.0/lib/esm/index.js';
```

It will crash because `index.js` will import `domutils` and `boolbase` as module name.

That wont let us to use this strategy in a solution using WebWorkers, Deno, or other remote importers.

An Importmap could solve the problem, but not for public services where we have old browsers in the workers desktops and in the public laptops, like mommy.

I propose to remove `boolbase` (replacing `falseFunc`, the only usage) and export a `defaltSetup()` func where `domutils` will be imported by import func, so will only be loaded if needed and if the environment allows it.
...or dist a full bundle.

**Comment by fb55** [comment]
This seems like a shortcoming of jsdelivr – have a look at eg. https://www.skypack.dev as an alternative.

**Comment by aurium** [comment]
Skypack totally solves the issue!

**Comment by aurium** [comment]
Skypack totally solves the issue!
