### ISSUE TITLE
Does not work with chrome since node.type:string doesn't exist on dom api

### ISSUE THREAD

**Issue by nojvek** [fb55/css-select#116]
not sure why you are testing for isTag as 
https://github.com/fb55/domelementtype/blob/master/index.js

```
isTag: function(elem){
		return elem.type === "tag" || elem.type === "script" || elem.type === "style";
	}
```

.type doesn't exist on dom api so CSSSelect will always return null.

**Comment by fb55** [comment]
You have to use an alternative adapter, eg. https://github.com/nrkn/css-select-browser-adapter
