### ISSUE TITLE
should the default adapter be one that's backed by a DOM?

### ISSUE THREAD

**Issue by leeoniya** [fb55/css-select#118]
hi @fb55 ,

i was wondering if the DOM adapter should be default (and part of this repo)?

the dom api is the common baseline implementation and i found it a bit surprising that it was not the default and that it was provided by a third party.

would you be open to making it the default and sucking it into this repo? cc @nrkn 

btw, `css-select` is awesome. i'm using it in https://github.com/leeoniya/dropcss with 0 issues. however, i'm finding that i need to submit pull requests to @nrkn [1] and asking him to publish to npm to be able to use it with [node-html-parser](https://www.npmjs.com/package/fast-html-parser). this seems somewhat odd. i would expect to submit fixes to the default [dom] adapter to this repo and have a new version published rather than adding another dependency that's in a satellite repo.

thanks!

[1] https://github.com/nrkn/css-select-browser-adapter/pull/3

**Comment by fb55** [comment]
Hi @leeoniya, generally I'm also not super fast to respond to issues, so you might have a better time with the two-repo approach. I would also be happy to pull this in, should there ever be a need.
