### ISSUE TITLE
Boolbase license

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [fb55/css-select#165]
Hello,

It looks like this package depends on the `boolbase` package, which doesn't contain a license file. Could you please add a LICENSE file to the `boolbase` package, to explicitly state what that package's license is?

Thanks,
Eli

**Comment by fb55** [comment]
https://github.com/fb55/boolbase/blob/master/LICENSE

**Comment by Bosch-Eli-Black** [comment]
Ah, sorry! It looks like the package that I was looking at was using v1.0.0 of boolbase, which didn't have the LICENSE file yet.

Thanks for the reply :)
