### ISSUE TITLE
Match selector string against AST?

### ISSUE THREAD

**Issue by strarsis** [fb55/css-select#175]
Let's say there is a selector string that could be used for `document.querySelector(All)`.
Is it possible to match that selector string against the CSS AST of a CSS Stylesheet (parsed by CSSTree)?
This is similar to using CSS selectors against DOM, but rather for a CSS AST.

**Comment by fb55** [comment]
This should be possible, you would have to convert the css-tree selector to the css-what format first, tho (or serialize the selector, then have it be parsed again). You can pass a parsed CSS selector in the css-what format directly to the exported functions.
