### ISSUE TITLE
css-select returns strange tag element when element is missing

### ISSUE THREAD

**Issue by 5saviahv** [fb55/css-select#182]
I have issue with cheerio, it throws error something about "Cant read property from undefined". 
What I do is: 
I have HTML similar to this: `<div class="rating">...<li>45</li>...</div>`
and selector is:
```
var cheerio = require('cheerio');
var $=cheerio.load(html);
var rating = cheerio.text( $('.rating li') );

```
and It works fine, but some cases there is rating but there is no `<li>` tag and this will throw.
after some detective work I realized cheerio returns little strange tag element in those cases and it comes really from css-select module:

This tag element has many properties and one of them is 'children' but it is function not array, like cheerio expects and it will throw error.

**Comment by fb55** [comment]
`$('.rating li')` returns an empty cheerio object. Cheerio has a `children` method, which is probably what you're seeing.

You should be able to get the same effect using

```js
var cheerio = require('cheerio');
var $=cheerio.load(html);
var rating = $('.rating li').text();
```

**Comment by 5saviahv** [comment]
You are probably right, this object looks very similar to Cheerios prototype, but I cant reproduce it in cheerio with empty arrays. I will dig out my case files where it happens and look what I find there.

**Comment by 5saviahv** [comment]
After some tests, yes It is not css-select, but cheerio.
