### ISSUE TITLE
Release a version with fresh deps

### ISSUE THREAD

**Issue by pahan35** [fb55/css-select#216]
@fb55 is there any chance to get a release with `"domutils": "^2.1.0"`?

I noticed that it was updated nearly 5 months ago, but there is no new release :(

**Comment by fb55** [comment]
There is a Typescript port pending that is supposed to be the next major release. Any reason why an earlier release would be helpful?

**Comment by pahan35** [comment]
The only benefit I see is that it'll prevent duplicating of `domutils` in https://github.com/TrySound/postcss-inline-svg/pull/74

However, I don't see activity there right now, so maybe there is no reason to do it right now.
