### ISSUE TITLE
Does this library query for nested elements?

### ISSUE THREAD

**Issue by vedantroy** [fb55/css-select#233]
I was trying out this library on some sample HTML & the selectors weren't matching (the reproduction is here: https://github.com/jsdom/jsdom/issues/3057, I was seeing if this library could replace JSDOM's css selector implementation)

Is this library recursive? E.g, can I pass in the `window` element & a CSS selector in order to find a deeply nested element?

**Comment by fb55** [comment]
It is, yes! Curious to see where this takes you.

**Comment by strarsis** [comment]
This library is very elegant, just an adapter has to be implemented (there is even a [base adapter](https://github.com/nrkn/css-select-base-adapter) to further reduce the required code (though one may forego some abstractions because of optimization).
