### ISSUE TITLE
Publish 1.1.0

### ISSUE THREAD

**Issue by jugglinmike** [fb55/css-select#29]
Hey Felix--I'm having some problems downstream, and I'm wondering if it was a bug fixed in 1.1.0. The latest version available on npm is 0.7.0. Could you publish the latest release?

**Comment by jugglinmike** [comment]
Actually, I can always check using a git URL. I'll leave this open because I expect you intended to publish the release but just forgot.

**Comment by fb55** [comment]
The module is now named `css-select`. Thanks for the reminder, though, I've added a deprecation notice for the old name to npm.

**Comment by jugglinmike** [comment]
Thanks! Sad to see the old school name go :P
