### ISSUE TITLE
Case insensitive :contains?

### ISSUE THREAD

**Issue by ganeshv** [fb55/css-select#33]
Is there a way to do a case insensitive :contains? If not, would :icontains be an acceptable enhancement? I'm willing to do the coding.

**Comment by fb55** [comment]
Having an `i` after the searched string might be a nice addition: Eg. `:contains("AnY WaY You wAnt To Spell" i)`. This is already implemented for attributes, but would require changes to css-what.

**Comment by ganeshv** [comment]
The possible issue with that syntax is

    :contains(anything i)
    :contains("anything" i)
    :contains("anything i")

would have different semantics, and are confusing at first glance. If :contains had historically forced the use of quotes, or had a different form (e.g. :contains=) it would be a simpler choice.

IMHO icontains is sort of familiar - Django uses it, and there is even a JQuery plugin to supplement its :contains selector called [jquery.icontains](https://github.com/KurtPreston/jquery.icontains)

**Comment by fb55** [comment]
I would only do a case-insensitive search for the second of your examples, but I see your point. The Django example isn't exactly for CSS selectors, but I would be fine with it. As always: Pull requests welcome :)

**Comment by ganeshv** [comment]
Hi @fb55, the code was pretty easy, but I could do with some guidance on adding tests. I assume you've copied tests from sizzle and qwery and so on. Which set should I insert the :icontains tests?

**Comment by fb55** [comment]
I would create a new file in the `test` directory (perhaps `icontains.js`), then use the format of [`attributes.js`](https://github.com/fb55/css-select/blob/d4c8ca19dd5003ee8add30b0e565656d3001c8e1/test/attributes.js), which already contains the case-insensitive test cases for attributes :).

**Comment by fb55** [comment]
Fixed in #34
