### ISSUE TITLE
Support :scope selector?

### ISSUE THREAD

**Issue by vedantroy** [fb55/css-select#343]
Does this project support: https://stackoverflow.com/questions/43354070/css-pseudo-selector-to-select-the-current-element-within-queryselector/43354126?

I didn' t see it in the list of supported selectors in the README, but maybe it's supported?

I believe `:root` probably does the same thing in this project, but `:scope` would be nice for browser compatability.

**Comment by fb55** [comment]
This actually is supported, I've added it to the README. Thanks for flagging!
