### ISSUE TITLE
Documentation: A list of all available selectors

### ISSUE THREAD

**Issue by matthewmueller** [fb55/css-select#4]
It'd be nice to have all the implemented selectors on one page for reference

**Comment by hollowdoor** [comment]
What about multiple attribute selectors. Like `a[href][name="somelink"]`.

**Comment by fb55** [comment]
All selectors can be used as often as you want to, in any order.
-- 
– Felix

**Comment by hollowdoor** [comment]
Ok cool. That was a freaking fast reply. I was wondering if that should be documented too. At least spelled out clearly for the comprehension impaired like me. I think my question was based on my misunderstanding of how selectors work. Like `a` is a selector, and `[href]` is a selector. `a[href]` is two selectors.

**Comment by t7yang** [comment]
I have an error with linkedom with internally using `css-select`

```
Error: :nth-last-child isn't part of CSS3
    at Object.compilePseudoSelector (...\node_modules\css-select\lib\pseudo-selectors\index.js:29:15)
    at Object.compileGeneralSelector (...\node_modules\css-select\lib\general.js:21:39)
    ...
```

https://github.com/WebReflection/linkedom/issues/58

**Comment by fb55** [comment]
@t7yang Responded in the other repo, thanks for flagging.
