### ISSUE TITLE
The library is old so I want you to update it.

### ISSUE THREAD

**Issue by famibee** [fb55/css-select#468]
Due to security issues, the library is out of date and I would like you to update it.
セキュリティの問題から、ライブラリが古いので更新して欲しいです。

| Lib | Now | Latest |
|---|---|---|
| css-what | 5.0.0 | 5.0.1 |

**Comment by fb55** [comment]
`css-select@4.1.3` includes that patch. Try upgrading your packages to the latest version.

**Comment by famibee** [comment]
https://github.com/fb55/css-select/blob/master/package.json

Look at the 25th line, it is ["css-what": "^ 5.0.0"].
25行目を見て欲しい、【"css-what": "^5.0.0"】になっています。

**Comment by fb55** [comment]
That range includes the relevant update. The `package-lock.json` file enforces the new version.

**Comment by famibee** [comment]
Thank you for your support.
