### ISSUE TITLE
after upgrade getting "parse is not a function error"

### ISSUE THREAD

**Issue by vkpraveen** [fb55/css-select#469]
After upgrade of package "css-what" to version "5.0.1" getting an error parse is not a function

Application is created using Create React app template

Error:

node_modules\css-select\lib\compile.js:31
var token = parse(selector, options);
^

TypeError: parse is not a function

Package version: "css-what": "5.0.1"

**Comment by vkpraveen** [comment]
Fixed by upgrade to the latest package

**Comment by shauryagupta30** [comment]
npm install -g npm stable

npm audit fix

solved my problem
