### ISSUE TITLE
depth option

### ISSUE THREAD

**Issue by matthewmueller** [fb55/css-select#5]
Hey man,

It'd be great to have an option to specify how deep the selection engine will crawl through the children. I think this would be a nice option at the selection level because it could improve performance for certain queries. 

For my use case, I'm implementing `$('#fruit').children('li')`, which will only want to search one level deep.

**Comment by StJohn3D** [comment]
+1

**Comment by fb55** [comment]
Querying is implemented outside of this library closing this (after almost 6 years!).
