### ISSUE TITLE
Question : Is there a way to select nodes with tag, class and ID selector in O(1) ?

### ISSUE THREAD

**Issue by abarre** [fb55/css-select#567]
Hello,
I am wondering if it is possible to improve the performance of basic selections with tag, class and ID selector to have a selection in O(1).

My understanding is that selections on ID, tag and class will result on walking through the entire tree (O(n)) with css-selector while this may be possible to retrieve the node directly from a pre-build map (O(1)).

My goal is to replicate the browser behavior. However, I didn't see much information on the browser implementation so may be completely wrong on how this selector are managed by the browser but I believe that there are some pre-build map that are creating for basic selector.

For instance, if htmlparser2 + domhandler receive this html 
```html
<body><div id="main"><div><span class="big">text</span></div><body>
```
I think that domhandler could create three maps while receiving node event from htmlparser2 : 
```
// pre-build-selection generated by domhandler

body : [{ name: body}]
div : [{ name: div, attr: {id: main}}, { name: div}]
span : [{ name: span, attr: {class: big}}]
.big : [{ name: span, attr: {class: big}}]
#main : [{ name: div, attr: {id: main}}]
```

Then css-selector could directly look up this map to get the nodes in O(1).
Of course, this will increase the memory size for sure.
Another alternative would be to give to domhandler the list of selector that should be prebuilt. For instance, if the program is only interested in `.big` node, we could only prebuild the selection for this selector.

**Comment by fb55** [comment]
There is the `cornet` module for exactly this use case: It queries for selectors while the DOM is being constructed. This has some drawbacks in terms of which selectors are supported; eg. `:last-child` will always be true, as the current node will always be the last one added to its parent.

Hope this helps!

**Comment by fb55** [comment]
Assuming this has been resolved.
