### ISSUE TITLE
Security Vulnerability: "nth-check" dependency

### ISSUE THREAD

**Issue by bchohon** [fb55/css-select#628]
Hello there!

The version of "nth-check" dependency referenced in the latest tagged release `v4.1.3` has a security vulnerability that is being flagged by Dependabot (see image below).

Looking through the repository, I see the patched version of "nth-check" has already been merged into #master.  However, there has not been a new release since the merge.  In turn, it looks like all that needs to occur to fix this security issue is to cut a new release version and publish to npm.  Thanks in advance!

### Details
- BAD VERSION: `nth-check#v2.0.0`
- PATCHED VERSION: `nth-check#v2.0.1`

![Screen Shot 2021-11-30 at 10 48 11 AM](https://user-images.githubusercontent.com/7060088/144109000-daa1c755-0ca3-40eb-9840-0afe9eaac33e.png)

**Comment by fb55** [comment]
See #622, #607, #599.

**Comment by bchohon** [comment]
Thanks @fb55
