### ISSUE TITLE
Support scoped-selections relative to root

### ISSUE THREAD

**Issue by ChristopherChudzicki** [fb55/css-select#709]
*Original post below. I originally misunderstood the issue*

The browswer-native methods [Element.querySelector](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector) and [Element.querySelectorAll](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) support scoped selections relative to the root. By this I mean that with a document like

```html
    <div class="parent">
      <div class="one"><p class="p1"></p></div>
      <div class="two"><p class="p2"></p></div>
      <div class="three"><p class="p3"></p></div>
    </div>
```
then:
```js
const two = document.querySelector('.two')
// query relative to parent, returns p2:
Q1 = two.querySelector('.parent .two .p2')

// but still scope limited... this returns null:
Q2 = two.querySelector('.parent .two .p3')
```

**Issue:** The most natural seeming way to mimic Q1 in `css-select` is `CSSselect('.parent .two .p2', parent)` but this returns null.

### Original message
*Leaving this, but it's based on my misunderstanding of the code example*

I'm attempting to replace an old usage of `cssauron` with `css-select` and came found the following discrepancy between `is` and `selectAll` when acting on children:

```ts
import * as CSSselect from "../src";
import { parseDOM } from "htmlparser2";
import type { Element } from "domhandler";

describe("selectAll", () => {
    it("behaves differently from `is` when called on children", () => {
        const [parent] = parseDOM("<div id=foo><p>foo</p></div>") as Element[];
        const child = parent.firstChild;

        // Passes
        expect(CSSselect.is(child, "div p")).toBe(true);
        // Fails. selectAll returns empty array; returns [child] if called in [parent]
        expect(CSSselect.selectAll("div p", [child])).toStrictEqual(child);
    });
});
```
In particular, I would have expected
1. `selectAll(query, [child])` to return matches if `is(child, query)` returns true, and
2. `selectAll(query, [child])` to return matches if `selectAll(query, [root])` returns `child` as part of its match. _Native Element.querySelector seems to behave this way._

The example above contradicts both of these expectations. Is the current behavior intended? Am I misunderstanding something?

Thanks for this library! I really appreciate the flexibility afforded by `adapter`.

**Comment by fb55** [comment]
`selectAll` limits the scope of the search to the passed elements. You can get the same effect by passing a context to `is`:

```js
expect(CSSselect.is(child, "div p", {context: [child]})).toBe(false);
```

**Comment by ChristopherChudzicki** [comment]
I am going to close this. I think I was wrong and understand better now.

```js
Q1 = two.querySelector('.parent .two .p2')
```
is akin to
```
CSSselect('.parent .two .p2', parent, { context: two })
```
Passing `parent` as the search space, and `two` as the context.

Thanks again. Really looking forward to replacing cssauron.

**Comment by fb55** [comment]
Thanks for the `querySelector` example! This behaviour is based on the rules for [Absolutizing a Relative Selector](https://www.w3.org/TR/selectors-4/#absolutizing); it seems like `css-select` is a bit over-eager with applying this to all selectors, not just relative ones. I will reopen this issue to track this.

**Comment by fb55** [comment]
I looked into this some more. `css-select` currently treats every selector as a relative selector, which is in line with the behaviour of the CSS selector engines it is modelled after (Sizzle & co.). To get the behaviour from `querySelector`, you can pass your document as the context:

```js
CSSselect('.parent .two .p2', parent, { context: document })
```

This will disable absolutizing.

I want to add an option to control this eventually.

**Comment by fb55** [comment]
There is now a `relativeSelector` option that can be used to disable absolutizing selectors.
