### ISSUE TITLE
Allow swapping of domutils

### ISSUE THREAD

**Issue by strarsis** [fb55/css-select#71]
To be able to use css-select against an AST that is different than the one from htmlparser2, 
the internally used domutils should be swappable for a different module (but with same API).

Currently I have to use mocking for replacing it:
```js
[...]
var mock        = require('mock-require'),
    domutilsAlt = require('../domutils-alt');
mock('domutils', domutilsAlt);
var cssSelect   = require('css-select');
[...]
````

**Comment by fb55** [comment]
This was implemented with #66, but I want to go through the code again before publishing a new version.
