### ISSUE TITLE
Release to npm

### ISSUE THREAD

**Issue by strarsis** [fb55/css-select#72]
@fb55: Now with added adapter option, it would be great to have the latest 
changes [released to npm](https://www.npmjs.com/package/css-select) so it can be directly used as npm package.

**Comment by martinjuhasz** [comment]
+1 for this!

**Comment by stefanmaric** [comment]
For reference, there's a pre-release under `1.3.0-rc0`: https://github.com/fb55/css-select/commit/e3aac04569197a9ee770a8aeadc3563f1eb85132

**Comment by strarsis** [comment]
The latest release of css-select on npm makes merging the inlineStyles PR for svgo possible.
Does this issue still make sense or can it be closed now because releases usually happen frequently anyway?

**Comment by fb55** [comment]
Closing in favour of #92
