### ISSUE TITLE
":not" selector returning too many results

### ISSUE THREAD

**Issue by philipp-classen** [fb55/css-select#742]
The `:not` selector returns too many results (three matches instead of two):

```
const { Parser } = require('htmlparser2');
const { DomHandler } = require("domhandler");
const CSSselect = require('css-select');

const html = `
  <html>
    <head></head>
    <body>
      <p>
        <table>
          <tbody>
            <tr>
              <td>
                <p></p>
              </td>
            </tr>
          </tbody>
        </table>
      </p>
      <p></p>
    </body>
  </html>
`;

const handler = new DomHandler((error, dom) => {
  if (error) {
    throw error;
  }
  const result = CSSselect.selectAll('p:not(table p)', dom);
  console.log(Object.entries(result).length);
});

const parser = new Parser(handler);
parser.write(html);
parser.end();
```

Expectation: should print 2
Actual result: prints 3

```
# package.json
{
  "dependencies": {
    "css-select": "^4.3.0",
    "domhandler": "^4.3.1",
    "htmlparser2": "^7.2.0"
  }
}
```

I'm using Node v16.14.2

---

Originally, I reported it in the linkedom library, which is based on css-select: https://github.com/WebReflection/linkedom/issues/126

Also, the example originates from a related [bug in jsdom](https://github.com/jsdom/jsdom/issues/3340), but fails in a different way: while linkedom filters out none of the elements (returning 3 instead of 2), jsdom filters all of them (returning 0 instead of 2). That bug report also includes a JSFiddle to check how the browser matches the html: https://jsfiddle.net/7v8dzgfh/6/

**Comment by fb55** [comment]
This is in line with the behavior of browsers: https://jsfiddle.net/4mqnrL70/

The reason for this is that your HTML actually has four `<p>` tags: The `<table>` tag closes the first `<p>` tag. The left-over `</p>` is then treated as `<p></p>`. Have a look at https://jsfiddle.net/4mqnrL70/1/ for how your browser deals with this.

**Comment by philipp-classen** [comment]
> This is in line with the behavior of browsers: https://jsfiddle.net/4mqnrL70/
> 
> The reason for this is that your HTML actually has four `<p>` tags: The `<table>` tag closes the first `<p>` tag. The left-over `</p>` is then treated as `<p></p>`. Have a look at https://jsfiddle.net/4mqnrL70/1/ for how your browser deals with this.

Thanks, for checking it quickly.  So, in other words, the HTML parser makes the difference in this example.

In Firefox, loading the html as a standalone website, leads to that structure (after innerHtml=innerHtml):

```
<p>
<table>
<tbody>
<tr>
<td>
<p></p>
</td>
</tr>
</tbody>
</table>
</p>
<p></p>
```

... while in JsFiddler, Firefox ends up with that (adding `</p` elements):

```
<p>
</p><table>
<tbody>
<tr>
<td>
<p></p>
</td>
</tr>
</tbody>
</table>
<p></p>
<p></p>
````

To sum it up, parsers differ between
* the NodeJs setup with htmlparser2
* Firefox when normally opening a page
* Firefox has it embedded it in the JsFiddle example

I get your point that it is then not the logic in css-select if the parser gives it different input to handle. Just wanted to be sure that I understood it.
