### ISSUE TITLE
Some functions of adapter don't differ between implementations

### ISSUE THREAD

**Issue by nrkn** [fb55/css-select#76]
Therefore you could require a smaller adapter surface and fill in the general functions if the adapter doesn't implement them already

I wasn't sure if `css-select` is the best place to do this, or if it should be standalone, so I created this:

https://github.com/nrkn/css-select-base-adapter

@fb55 if you think this would be good in `css-select` I will add it, update the readme and submit a PR

Otherwise, maybe just add a link to the base adapter repo in the readme under adapters?

**Comment by fb55** [comment]
This was added to the readme.
