### ISSUE TITLE
Adapter API: Return for not found/empty

### ISSUE THREAD

**Issue by strarsis** [fb55/css-select#77]
It would be helpful if it is clarified, what an adapter API should return 
when no element was found or as  an empty result.

For arrays this is quite probably just an empty array ([]).
But when a single node/element is expected to be returned, this is less clear, 
like for getParent where this will usually happen for the root node (which got no parent) or 
for getText which could return just an empty string or something non-string like (like null) 
to indicate that there is no text at all for this node.

Adapter methods where this should be clarified:
getAttributeValue; getName; getParent; getText; findOne
What should these return if nothing (no element or attribute(value)) was found? - 
false, null, undefined, an empty string or generally something 'false-y'?

**Comment by fb55** [comment]
Good point! For `getAttributeValue`, `getParent` and `findOne`, `null` would be appropriate, for `getText` the empty string. `getName` has never been an issue here, but either an empty string or even `NaN` would be appropriate.

Leaving this open as a reminder to add this to the readme.

**Comment by strarsis** [comment]
And there is also another related question: When should isTag(...) return true or false?
When the node in question resulted from an element consisting of tags that are valid in the markup language (like svg or html)?
Should it return false for special elements like pseudo-elements, shadow-dom elements or inner nodes for text (e.g. styles content/cdata)?
