### ISSUE TITLE
custom HTML gets interpreted as pseudo selector

### ISSUE THREAD

**Issue by MartinMuzatko** [fb55/css-select#79]
Hello! I'm trying to parse HTML provided through Atlassian Confluence. Which uses custom HTML elements like `<ac:structured-macro ac:name="details">`

When selecting this element with a selector like `ac:structured-macro` I get the following error:

```
SyntaxError: unmatched pseudo-class :structured-macro
at module.exports.compile (as pseudo) in css-select/lib/pseudos.js — line 388
```

Is there an option where I can allow this kind of HTML and/or escape the colon?

Thank you!

**Comment by strarsis** [comment]
https://github.com/cheeriojs/cheerio/issues/697

**Comment by MartinMuzatko** [comment]
Awesome! This works. I reported the problem here, since when using cheerio, it is thrown in the package css-select.

Thank you a lot!
