### ISSUE TITLE
Pseudo-Elements data

### ISSUE THREAD

**Issue by strarsis** [fb55/css-select#83]
Concerning the validation for css pseudos in https://github.com/fb55/css-select/blob/master/lib/pseudos.js#L372

CSS information from MDN data repository can be used:
https://github.com/mdn/data/blob/master/css/selectors.json

**Comment by fb55** [comment]
Nice find :)

Right now I would rather remove the strict mode than make it work properly (I honestly can't remember why I implemented it in the first place), but that list is a great resource anyway.
