### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by chriseppstein** [fb55/css-select#92]
Can you release the latest changes? I have a package I need to release that depends on it.

**Comment by chriseppstein** [comment]
Also: if you could set your license to one of the official licenses listed here: https://spdx.org/licenses/ it would make it easier for people to use it. Lots of companies validate licenses against that list.

**Comment by chriseppstein** [comment]
Note: you'll need to add the typescript definition to the package.json: https://github.com/chriseppstein/css-select/commit/47d2850d7c410055d79cf248b069f4437353e2e5

**Comment by SimonSchick** [comment]
Yea, a release would be neat.

**Comment by chriseppstein** [comment]
@fb55 I will be releasing my dependent project soon that requires recent changes. is there some way I can help maintain this project, I really don't want to have to release a fork.

**Comment by fb55** [comment]
I would prefer to update to the latest domutils version first, as it includes a bunch of important changes. Tests run out of memory though, which I haven't found time to investigate yet.

**Comment by chriseppstein** [comment]
@fb55 do you have a WIP branch for the upgrade?

**Comment by fb55** [comment]
#85 and #90 try to do this, and tests fail for both

**Comment by chriseppstein** [comment]
ok. I'm super busy, but if I can find the time to investigate, I'll poke around.

**Comment by fb55** [comment]
That would be amazing. As soon as that's done I'm happy to publish a new release.

**Comment by chriseppstein** [comment]
@fb55 I've made partial progress: https://github.com/fb55/css-select/pull/96

**Comment by chriseppstein** [comment]
@fb55 ok. if you land https://github.com/fb55/domutils/pull/34 and https://github.com/fb55/css-select/pull/96 I think you can release this now.

I have more plans for contributions to this project, if you want to give me commit access, I'd be happy to help maintain this project.

**Comment by fb55** [comment]
@chriseppstein Gave you commit access, would love some help with maintaining this :)

**Comment by chriseppstein** [comment]
@fb55 I don't seem to have commit access. Also, if you want me to be able to push releases, I'll need to be added to the npm package. same username.

**Comment by fb55** [comment]
@chriseppstein You should have received an email — I invited you again, hope that works. Also added you as an author on npm.

**Comment by chriseppstein** [comment]
@fb55 🎉 ok I think I've got it sorted out!

**Comment by fb55** [comment]
Fixed in f292b0b
