### ISSUE TITLE
Timetable or workaround for namespaced tag names

### ISSUE THREAD

**Issue by herrKlein** [fb55/css-select#927]
In my search to manipulate XML on server and browser, I ran into the cheerio lib. With enthusiasm I learned about cheerio and css-select and what it could do for my project ( while avoiding xpath and xslt ).
Sadly I soon hit a wall cause  In this example I need to query the mathml tags. But I don't know the namespace beforehand. 
It could be any namespace, in this example ```m:``` or even ```mth:```

**m:**
```
<?xml version="1.0" encoding="utf-8" ?>
<test-assesment xmlns:m="http://www.w3.org/1998/Math/MathML">
  <m:math>
    <m:mo>A</m:mo>
  </m:math>
</test-assesment>
```

**mth:**
```
<?xml version="1.0" encoding="utf-8" ?>
<test-assesment xmlns:mth="http://www.w3.org/1998/Math/MathML">
  <mth:math>
    <mth:mo>A</mth:mo>
  </mth:math>
</test-assesment>
```

But this selector: ```$('*|math')``` is not implemented yet.
_"Namespaced tag names are not yet supported by css-select"_

Then I tried getting the namespace by querying the xmlns attributes, but I ran into the same problem. I would retreive the namespace which belonged to MathML: 'http://www.w3.org/1998/Math/MathML'. And then use that namespace, wether it would be 'm:' or 'mth:' in my followup query for the elements. 
Is there a timetable for namespaced tag names, or did I miss something which can solve my problem.

**Comment by fb55** [comment]
PRs for are welcome! I don't have any plans to implement this, but would love to support someone that wants to contribute namespace support.

Your best bet is probably to add a custom pseudo-selector, following eg. https://github.com/fb55/css-select/blob/d8d92e395da44387e0fb177a026ee2a669b3ef58/test/api.ts#L168-L178

**Comment by herrKlein** [comment]
Thanks for the reply, If i'll have time I will look into it.
I also found out cheerio does not work in the browser. So thats putting a stop into going this route, still searching to manipulate xml on server and client with the same code and using a jquery like syntax

**Comment by fb55** [comment]
Cheerio does work in the browser, please file an issue if you encounter an blockers.
